# Generated by Django 6.0.2 on 2026-03-14 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0004_alter_recipient_email_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="recipient",
            options={
                "permissions": [("can_disable_recipient", "Can disable recipient")],
                "verbose_name": "Получатель",
                "verbose_name_plural": "Получатели",
            },
        ),
    ]
