# Generated by Django 5.2.9 on 2026-03-01 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailings", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mailingattempt",
            options={"verbose_name": "Попытка отправки письма", "verbose_name_plural": "Попытки отправки писем"},
        ),
    ]
