# Generated by Django 6.0.2 on 2026-03-04 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0001_initial"),
        ("mailings", "0002_alter_mailingattempt_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mailingattempt",
            options={
                "ordering": ["-attempt_time"],
                "verbose_name": "Попытка отправки письма",
                "verbose_name_plural": "Попытки отправки писем",
            },
        ),
        migrations.AlterField(
            model_name="mailing",
            name="status",
            field=models.CharField(
                choices=[("created", "Создана"), ("active", "Запущена"), ("finished", "Завершена")],
                default="created",
                max_length=20,
                verbose_name="Статус",
            ),
        ),
        migrations.AlterField(
            model_name="mailingattempt",
            name="attempt_time",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Дата и время попытки"),
        ),
        migrations.AlterField(
            model_name="mailingattempt",
            name="mailing",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attempts",
                to="mailings.mailing",
                verbose_name="Рассылка",
            ),
        ),
        migrations.AlterField(
            model_name="mailingattempt",
            name="recipient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attempts",
                to="clients.recipient",
                verbose_name="Получатель",
            ),
        ),
        migrations.AlterField(
            model_name="mailingattempt",
            name="server_response",
            field=models.TextField(blank=True, verbose_name="Ответ почтового сервера"),
        ),
        migrations.AlterField(
            model_name="mailingattempt",
            name="status",
            field=models.CharField(
                choices=[("success", "Успешно"), ("failed", "Не успешно")], max_length=10, verbose_name="Статус"
            ),
        ),
    ]
