# Generated by Django 6.0.2 on 2026-03-11 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailings", "0005_message_owner"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mailing",
            options={
                "permissions": [("disable_mailing", "Can disable mailing")],
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
            },
        ),
    ]
