# Generated by Django 6.0.2 on 2026-03-14 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailings", "0006_alter_mailing_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="message",
            options={
                "permissions": [("can_disable_message", "Can disable message")],
                "verbose_name": "Сообщение",
                "verbose_name_plural": "Сообщения",
            },
        ),
    ]
